/*
  DSC Studio
  Copyright (C) 2022-2025 nastys & keikei14

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// opcodes re'd by korenkonder
let db_f2 = {
    "0":{"opcode":"END","len":0},
    "1":{"opcode":"TIME","len":1},
    "2":{"opcode":"MIKU_MOVE","len":4},
    "3":{"opcode":"MIKU_ROT","len":2},
    "4":{"opcode":"MIKU_DISP","len":2},
    "5":{"opcode":"MIKU_SHADOW","len":2},
    "6":{"opcode":"TARGET","len":12},
    "7":{"opcode":"SET_MOTION","len":4},
    "8":{"opcode":"SET_PLAYDATA","len":2},
    "9":{"opcode":"EFFECT","len":6},
    "10":{"opcode":"FADEIN_FIELD","len":2},
    "11":{"opcode":"EFFECT_OFF","len":1},
    "12":{"opcode":"SET_CAMERA","len":6},
    "13":{"opcode":"DATA_CAMERA","len":2},
    "14":{"opcode":"CHANGE_FIELD","len":2},
    "15":{"opcode":"HIDE_FIELD","len":1},
    "16":{"opcode":"MOVE_FIELD","len":3},
    "17":{"opcode":"FADEOUT_FIELD","len":2},
    "18":{"opcode":"EYE_ANIM","len":3},
    "19":{"opcode":"MOUTH_ANIM","len":5},
    "20":{"opcode":"HAND_ANIM","len":5},
    "21":{"opcode":"LOOK_ANIM","len":4},
    "22":{"opcode":"EXPRESSION","len":4},
    "23":{"opcode":"LOOK_CAMERA","len":5},
    "24":{"opcode":"LYRIC","len":2},
    "25":{"opcode":"MUSIC_PLAY","len":0},
    "26":{"opcode":"MODE_SELECT","len":2},
    "27":{"opcode":"EDIT_MOTION","len":4},
    "28":{"opcode":"BAR_TIME_SET","len":2},
    "29":{"opcode":"SHADOWHEIGHT","len":2},
    "30":{"opcode":"EDIT_FACE","len":1},
    "31":{"opcode":"MOVE_CAMERA","len":21},
    "32":{"opcode":"PV_END","len":0},
    "33":{"opcode":"SHADOWPOS","len":3},
    "34":{"opcode":"EDIT_LYRIC","len":2},
    "35":{"opcode":"EDIT_TARGET","len":5},
    "36":{"opcode":"EDIT_MOUTH","len":1},
    "37":{"opcode":"SET_CHARA","len":1},
    "38":{"opcode":"EDIT_MOVE","len":7},
    "39":{"opcode":"EDIT_SHADOW","len":1},
    "40":{"opcode":"EDIT_EYELID","len":1},
    "41":{"opcode":"EDIT_EYE","len":2},
    "42":{"opcode":"EDIT_ITEM","len":1},
    "43":{"opcode":"EDIT_EFFECT","len":2},
    "44":{"opcode":"EDIT_DISP","len":1},
    "45":{"opcode":"EDIT_HAND_ANIM","len":2},
    "46":{"opcode":"AIM","len":3},
    "47":{"opcode":"HAND_ITEM","len":3},
    "48":{"opcode":"EDIT_BLUSH","len":1},
    "49":{"opcode":"NEAR_CLIP","len":2},
    "50":{"opcode":"CLOTH_WET","len":2},
    "51":{"opcode":"LIGHT_ROT","len":3},
    "52":{"opcode":"SCENE_FADE","len":6},
    "53":{"opcode":"TONE_TRANS","len":6},
    "54":{"opcode":"SATURATE","len":1},
    "55":{"opcode":"FADE_MODE","len":1},
    "56":{"opcode":"AUTO_BLINK","len":2},
    "57":{"opcode":"PARTS_DISP","len":3},
    "58":{"opcode":"TARGET_FLYING_TIME","len":1},
    "59":{"opcode":"CHARA_SIZE","len":2},
    "60":{"opcode":"CHARA_HEIGHT_ADJUST","len":2},
    "61":{"opcode":"ITEM_ANIM","len":4},
    "62":{"opcode":"CHARA_POS_ADJUST","len":4},
    "63":{"opcode":"SCENE_ROT","len":1},
    "64":{"opcode":"EDIT_MOT_SMOOTH_LEN","len":2},
    "65":{"opcode":"PV_BRANCH_MODE","len":1},
    "66":{"opcode":"DATA_CAMERA_START","len":2},
    "67":{"opcode":"MOVIE_PLAY","len":1},
    "68":{"opcode":"MOVIE_DISP","len":1},
    "69":{"opcode":"WIND","len":3},
    "70":{"opcode":"OSAGE_STEP","len":3},
    "71":{"opcode":"OSAGE_MV_CCL","len":3},
    "72":{"opcode":"CHARA_COLOR","len":2},
    "73":{"opcode":"SE_EFFECT","len":1},
    "74":{"opcode":"EDIT_MOVE_XYZ","len":9},
    "75":{"opcode":"EDIT_EYELID_ANIM","len":3},
    "76":{"opcode":"EDIT_INSTRUMENT_ITEM","len":2},
    "77":{"opcode":"EDIT_MOTION_LOOP","len":4},
    "78":{"opcode":"EDIT_EXPRESSION","len":2},
    "79":{"opcode":"EDIT_EYE_ANIM","len":3},
    "80":{"opcode":"EDIT_MOUTH_ANIM","len":2},
    "81":{"opcode":"EDIT_CAMERA","len":22},
    "82":{"opcode":"EDIT_MODE_SELECT","len":1},
    "83":{"opcode":"PV_END_FADEOUT","len":2},
    "84":{"opcode":"RESERVE0","len":1},
    "85":{"opcode":"RESERVE1","len":6},
    "86":{"opcode":"RESERVE2","len":1},
    "87":{"opcode":"RESERVE3","len":9},
    "88":{"opcode":"PV_AUTH_LIGHT_PRIORITY","len":2},
    "89":{"opcode":"PV_CHARA_LIGHT","len":3},
    "90":{"opcode":"PV_STAGE_LIGHT","len":3},
    "91":{"opcode":"TARGET_EFFECT","len":11},
    "92":{"opcode":"FOG","len":3},
    "93":{"opcode":"BLOOM","len":2},
    "94":{"opcode":"COLOR_CORRECTION","len":3},
    "95":{"opcode":"DOF","len":3},
    "96":{"opcode":"CHARA_ALPHA","len":4},
    "97":{"opcode":"AUTO_CAPTURE_BEGIN","len":1},
    "98":{"opcode":"MANUAL_CAPTURE","len":1},
    "99":{"opcode":"TOON_EDGE","len":3},
    "100":{"opcode":"SHIMMER","len":3},
    "101":{"opcode":"ITEM_ALPHA","len":4},
    "102":{"opcode":"MOVIE_CUT","len":1},
    "103":{"opcode":"EDIT_CAMERA_BOX","len":112},
    "104":{"opcode":"EDIT_STAGE_PARAM","len":1},
    "105":{"opcode":"EDIT_CHANGE_FIELD","len":1},
    "106":{"opcode":"MIKUDAYO_ADJUST","len":7},
    "107":{"opcode":"LYRIC_2","len":2},
    "108":{"opcode":"LYRIC_READ","len":2},
    "109":{"opcode":"LYRIC_READ_2","len":2},
    "110":{"opcode":"ANNOTATION","len":5}
};